- name: Configure BGP on Cisco NX-OS router nxos-02
  hosts: nxos-01
  gather_facts: false
  tasks:
  

    - name: configuring bgp in nxos-01
      cisco.nxos.nxos_bgp_global:
        config:
          router_id: "1.1.1.1"
          as_number: 65000
          
          neighbors:
              - neighbor_address: 192.168.255.189
                remote_as: 65001
        

    

- name: Configure BGP on Cisco NX-OS router nxos-02
  hosts: nxos-02
  gather_facts: no
  tasks:
  
   
    - name: config bgp in nxos-02
      cisco.nxos.nxos_bgp_global:
        config:
          router_id: "2.2.2.2"
          
          as_number: 65001
          neighbors:
              - neighbor_address: 192.168.255.201
                remote_as: 65000
                

- name: configure address family in bgp
  hosts: nx_os
  gather_facts: no
  tasks:
    - name: config
      cisco.nxos.nxos_bgp_address_family:
        config:
          address_family:
            - afi: ipv4
              safi: unicast
              
- name: configuring neighbor address family in nxos-01
  hosts: nxos-01
  gather_facts: false
  tasks: 
    - name: config address family in neighbor
      cisco.nxos.nxos_bgp_neighbor_address_family:
        config:
          as_number: 65000
          neighbors:
            - neighbor_address: 192.168.255.189
              address_family:
                - afi: ipv4
                  safi: unicast

- name: configuring neighbor address family in nxos-02
  hosts: nxos-02
  gather_facts: no
  tasks: 
    - name: config address family in neighbor
      cisco.nxos.nxos_bgp_neighbor_address_family:
        config:
          as_number: 65001
          neighbors:
            - neighbor_address: 192.168.255.201
              address_family:
                - afi: ipv4
                  safi: unicast





